# Generated by Django 5.2.6 on 2025-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myunisite', '0002_department_teacher_program_discipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
            ],
        ),
    ]
